language: node_js
node_js: 8
script:
- npm run build
- ls -a
deploy:
  provider: npm
  email: bryphe@outlook.com
  api_key:
    secure: R3JCd8jz8b30NO65UzTYdUwd8/j+lHxlAel9I7rtvatFLjgwQsweB1bYn76k6P09HwqXnlwsUlq2idIHcs8XdP0VruRyDzxDxsGWWTC9iyTk3WE7hd20RxQrORru9O5XhTuQ/e2e+FpRPSgFtKc+M4IrQ2jJh1jjvNlHVT/BznaQXnilKfCjGhXmk9pR35WLpSkhowWg1mfBh1VBz9bbqMHfiTOUEmEFXML1CUdEc5CTWfBJdb1/6aFAoHN+rp3zjAlFkaxHigdpZIyPFCvsUDzqC+NtqdMgTGzef1JTIrPIC+G2on/LfqE5mdzKrIIZWOWI1eKhBc0jIfEL2lVmfkGHJHTNLJtUPumlse0s3oJ2xH1y2L6Zn3iNV1k0WknUZ6VWv+dLS4x0IDaCWqy/F+xeDRirTuMYw6KTvthQlAMA3fl8b5IOsXvpV1ToIPg/O76+qvDMuj+uVvZFJmL3a7BDzOiP7H44TRSYNna6cCpmYO3JMJURYyQ+yZYBUEsw3KKcOwQp+88MAMndos7xBZKudqhddQnmA48yq2i1rJGK83SUDCS6CPsg0n1joFfPbLJ7bs7impxeGBF/3URYdCME3BH1nKy+WDUVyIGQwoRSONbDQsI0b8zUF5r1eX61t92Y3F41RBXlhgdkgkO8jcl9+VjKCrG1CQPvdIi5LG8=
  on:
    tags: true
    repo: onivim/oni-api
